const cardActions = {
  Cellar: [],
  Chapel: [],
  Moat: [{ type: "DRAW_CARDS", data: { drawAmount: 2 } }],
  Harbinger: [],
  Merchant: [],
  Vassal: [],
  Village: [],
  Workshop: [],
  Bureaucrat: [],
  Gardens: [],
  Militia: [],
  Moneylender: [],
  Poacher: [],
  Remodel: [],
  Smithy: [{ type: "DRAW_CARDS", data: { drawAmount: 3 } }],
  "Throne Room": [],
  Bandit: [],
  "Council Room": [],
  Festival: [],
  Laboratory: [],
  Library: [],
  Market: [],
  Mine: [],
  Sentry: [],
  Witch: [],
  Artisan: []
};

export default cardActions;
