const kingdomCards = [
  "Cellar",
  "Chapel",
  "Moat",
  "Harbinger",
  "Merchant",
  // "Vassal",
  // "Village",
  // "Workshop",
  // "Bureaucrat",
  // "Gardens",
  // "Militia",
  // "Moneylender",
  // "Poacher",
  // "Remodel",
  // "Smithy",
  // "Throne Room",
  // "Bandit",
  // "Council Room",
  // "Festival",
  "Laboratory",
  "Library",
  "Market",
  "Mine",
  "Sentry",
  "Witch",
  "Artisan"
];

export default kingdomCards;
